# Generated by Django 4.1.7 on 2023-08-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0003_campaign_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='profile_pic',
            field=models.ImageField(upload_to='media/affiliates/profile_pics'),
        ),
    ]
