# Generated by Django 4.1.7 on 2023-08-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0004_alter_affiliate_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='profile_pic',
            field=models.ImageField(upload_to='affiliates/profile_pics'),
        ),
    ]
