# Generated by Django 4.1.7 on 2023-08-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0005_alter_affiliate_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('conatct_position', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('facebook', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('youtube', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='Partner/logo')),
                ('facebook_followers', models.IntegerField(default=0)),
                ('twitter_followers', models.IntegerField(default=0)),
                ('instagram_followers', models.IntegerField(default=0)),
                ('youtube_subscribers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
