# Generated by Django 4.1.7 on 2023-08-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0006_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='facebook_followers',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='instagram_followers',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='twitter_followers',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='youtube_subscribers',
        ),
    ]
