# Generated by Django 4.1.7 on 2023-08-12 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0007_remove_partner_facebook_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='type',
            field=models.CharField(choices=[('agency', 'agency'), ('brand', 'brand'), ('seller', 'seller')], default='brand', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_affiliate', to='affiliate.affiliate'),
        ),
        migrations.AlterField(
            model_name='post',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_campaign', to='affiliate.campaign'),
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('promo_code', 'Promotional Code'), ('dynamic_link', 'Dynamic Link')], max_length=25)),
                ('promo_code', models.CharField(max_length=25, null=True)),
                ('dynamic_link', models.URLField(max_length=300, null=True)),
                ('commission_type', models.CharField(choices=[('percentage', 'percentage'), ('fixed_fee', 'fixed_fee')], max_length=25)),
                ('commission_rate', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('promo_code_conv', models.IntegerField(default=0)),
                ('dynamic_link_conv', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('money_paid_per_post', models.IntegerField(default=0)),
                ('spending', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='affiliate.affiliate')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='affiliate.campaign')),
            ],
        ),
    ]
