# Generated by Django 4.1.7 on 2023-08-12 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0008_partner_type_alter_post_affiliate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_month', models.DateField()),
                ('payment_status', models.CharField(choices=[('open', 'Open'), ('not_paid', 'Not Piad'), ('paid', 'Paid')], max_length=25)),
                ('payment_method', models.CharField(choices=[('wallet', 'Wallet'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], max_length=25)),
                ('payment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_received', to='affiliate.affiliate')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='affiliate.campaign')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_sent', to='affiliate.partner')),
            ],
        ),
    ]
